module.exports = {
  sources: {
    head: {
      droop: "https://kemono.cafe/wp-content/uploads/2020/05/kona_head_droop.png",
      flop: "https://kemono.cafe/wp-content/uploads/2020/05/kona_head_flop.png",
      normal: "https://kemono.cafe/wp-content/uploads/2020/05/kona_head_normal.png",
      perked: "https://kemono.cafe/wp-content/uploads/2020/05/kona_head_perked.png",
    },
    eyebrow: {
      angry: "https://kemono.cafe/wp-content/uploads/2020/05/kona_eyebrow_angry.png",
      normal: "https://kemono.cafe/wp-content/uploads/2020/05/kona_eyebrow_normal.png",
      puzzled: "https://kemono.cafe/wp-content/uploads/2020/05/kona_eyebrow_puzzled.png",
      sad: "https://kemono.cafe/wp-content/uploads/2020/05/kona_eyebrow_sad.png",
      surprised: "https://kemono.cafe/wp-content/uploads/2020/05/kona_eyebrow_surprised.png",
    },
    eyes: {
      doubt: "https://kemono.cafe/wp-content/uploads/2020/05/kona_eyes_doubt.png",
      glee: "https://kemono.cafe/wp-content/uploads/2020/05/kona_eyes_glee.png",
      happy: "https://kemono.cafe/wp-content/uploads/2020/05/kona_eyes_happy.png",
      lookaway: "https://kemono.cafe/wp-content/uploads/2020/05/kona_eyes_lookaway.png",
      normal: "https://kemono.cafe/wp-content/uploads/2020/05/kona_eyes_normal.png",
      shock: "https://kemono.cafe/wp-content/uploads/2020/05/kona_eyes_shock.png",
      squint: "https://kemono.cafe/wp-content/uploads/2020/05/kona_eyes_squint.png",
      uu: "https://kemono.cafe/wp-content/uploads/2020/05/kona_eyes_uu.png",
    },
    mouth: {
      formal: "https://kemono.cafe/wp-content/uploads/2020/05/kona_mouth_formal.png",
      pout: "https://kemono.cafe/wp-content/uploads/2020/05/kona_mouth_pout.png",
      serious: "https://kemono.cafe/wp-content/uploads/2020/05/kona_mouth_serious.png",
      smile: "https://kemono.cafe/wp-content/uploads/2020/05/kona_mouth_smile.png",
      smileopen: "https://kemono.cafe/wp-content/uploads/2020/05/kona_mouth_smileopen.png",
      widesmile: "https://kemono.cafe/wp-content/uploads/2020/05/kona_mouth_widesmile.png",
    },
  },
  emotes: [
    {
      key: "kona_careful",
      character: "kona",
      head: "normal",
      eyebrow: "normal",
      eyes: "glee",
      mouth: "pout",
    },
    {
      key: "kona_confident",
      character: "kona",
      head: "normal",
      eyebrow: "normal",
      eyes: "normal",
      mouth: "widesmile",
    },
    {
      key: "kona_cry",
      character: "kona",
      head: "droop",
      eyebrow: "sad",
      eyes: "uu",
      mouth: "pout",
    },
    {
      key: "kona_defeated",
      character: "kona",
      head: "droop",
      eyebrow: "angry",
      eyes: "uu",
      mouth: "formal",
    },
    {
      key: "kona_explain",
      character: "kona",
      head: "normal",
      eyebrow: "surprised",
      eyes: "normal",
      mouth: "formal",
    },
    {
      key: "kona_frustrated",
      character: "kona",
      head: "flop",
      eyebrow: "angry",
      eyes: "normal",
      mouth: "serious",
    },
    {
      key: "kona_happy",
      character: "kona",
      head: "perked",
      eyebrow: "surprised",
      eyes: "glee",
      mouth: "widesmile",
    },
    {
      key: "kona_oh",
      character: "kona",
      head: "normal",
      eyebrow: "normal",
      eyes: "glee",
      mouth: "pout",
    },
    {
      key: "kona_playful",
      character: "kona",
      head: "flop",
      eyebrow: "normal",
      eyes: "happy",
      mouth: "widesmile",
    },
    {
      key: "kona_pleased",
      character: "kona",
      head: "perked",
      eyebrow: "surprised",
      eyes: "happy",
      mouth: "smileopen",
    },
    {
      key: "kona_scream",
      character: "kona",
      head: "perked",
      eyebrow: "angry",
      eyes: "glee",
      mouth: "serious",
    },
    {
      key: "kona_sincere",
      character: "kona",
      head: "normal",
      eyebrow: "normal",
      eyes: "glee",
      mouth: "smile",
    },
    {
      key: "kona_soars",
      character: "kona",
      head: "normal",
      eyebrow: "normal",
      eyes: "glee",
      mouth: "smileopen",
    },
    {
      key: "kona_thinking",
      character: "kona",
      head: "perked",
      eyebrow: "puzzled",
      eyes: "uu",
      mouth: "formal",
    },
    {
      key: "kona_worried",
      character: "kona",
      head: "normal",
      eyebrow: "normal",
      eyes: "glee",
      mouth: "pout",
    },
  ],
};
