module.exports = {
  sources: {
    head: {
      droop: "https://kemono.cafe/wp-content/uploads/2020/05/maxine_head_droop.png",
      flop: "https://kemono.cafe/wp-content/uploads/2020/05/maxine_head_flop.png",
      normal: "https://kemono.cafe/wp-content/uploads/2020/05/maxine_head_normal.png",
      perked: "https://kemono.cafe/wp-content/uploads/2020/05/maxine_head_perked.png",
    },
    eyebrow: {
      angry: "https://kemono.cafe/wp-content/uploads/2020/05/maxine_eyebrow_angry.png",
      normal: "https://kemono.cafe/wp-content/uploads/2020/05/maxine_eyebrow_normal.png",
      puzzled: "https://kemono.cafe/wp-content/uploads/2020/05/maxine_eyebrow_puzzled.png",
      sad: "https://kemono.cafe/wp-content/uploads/2020/05/maxine_eyebrow_sad.png",
    },
    eyes: {
      angry: "https://kemono.cafe/wp-content/uploads/2020/05/maxine_eyes_angry.png",
      gleam: "https://kemono.cafe/wp-content/uploads/2020/05/maxine_eyes_gleam.png",
      glee: "https://kemono.cafe/wp-content/uploads/2020/05/maxine_eyes_glee.png",
      happy: "https://kemono.cafe/wp-content/uploads/2020/05/maxine_eyes_happy.png",
      lookaway: "https://kemono.cafe/wp-content/uploads/2020/05/maxine_eyes_lookaway.png",
      normal: "https://kemono.cafe/wp-content/uploads/2020/05/maxine_eyes_normal.png",
      shock: "https://kemono.cafe/wp-content/uploads/2020/05/maxine_eyes_shock.png",
      sneak: "https://kemono.cafe/wp-content/uploads/2020/05/maxine_eyes_sneak.png",
      uu: "https://kemono.cafe/wp-content/uploads/2020/05/maxine_eyes_uu.png",
    },
    mouth: {
      grin: "https://kemono.cafe/wp-content/uploads/2020/05/maxine_mouth_grin.png",
      oh: "https://kemono.cafe/wp-content/uploads/2020/05/maxine_mouth_oh.png",
      pout: "https://kemono.cafe/wp-content/uploads/2020/05/maxine_mouth_put.png",
      serious: "https://kemono.cafe/wp-content/uploads/2020/05/maxine_mouth_serious.png",
      smile: "https://kemono.cafe/wp-content/uploads/2020/05/maxine_mouth_smile.png",
      smileopen: "https://kemono.cafe/wp-content/uploads/2020/05/maxine_mouth_smileopen.png",
      yell: "https://kemono.cafe/wp-content/uploads/2020/05/maxine_mouth_yell.png",
    },
  },
  emotes: [
    {
      key: "maxine_awe",
      character: "maxine",
      head: "perked",
      eyebrow: "normal",
      eyes: "glee",
      mouth: "oh",
    },
    {
      key: "maxine_chaching",
      character: "maxine",
      head: "normal",
      eyebrow: "normal",
      eyes: "gleam",
      mouth: "grin",
    },
    {
      key: "maxine_grumpy",
      character: "maxine",
      head: "droop",
      eyebrow: "angry",
      eyes: "angry",
      mouth: "pout",
    },
    {
      key: "maxine_lament",
      character: "maxine",
      head: "flop",
      eyebrow: "angry",
      eyes: "angry",
      mouth: "oh",
    },
    {
      key: "maxine_normal",
      character: "maxine",
      head: "normal",
      eyebrow: "normal",
      eyes: "normal",
      mouth: "smile",
    },
    {
      key: "maxine_order",
      character: "maxine",
      head: "normal",
      eyebrow: "normal",
      eyes: "normal",
      mouth: "oh",
    },
    {
      key: "maxine_playful",
      character: "maxine",
      head: "normal",
      eyebrow: "normal",
      eyes: "happy",
      mouth: "smileopen",
    },
    {
      key: "maxine_smug",
      character: "maxine",
      head: "flop",
      eyebrow: "normal",
      eyes: "glee",
      mouth: "grin",
    },
    {
      key: "maxine_thinking",
      character: "maxine",
      head: "normal",
      eyebrow: "normal",
      eyes: "uu",
      mouth: "pout",
    },
    {
      key: "maxine_womp",
      character: "maxine",
      head: "flop",
      eyebrow: "sad",
      eyes: "sneak",
      mouth: "grin",
    },
    {
      key: "maxine_worried",
      character: "maxine",
      head: "normal",
      eyebrow: "normal",
      eyes: "lookaway",
      mouth: "serious",
    },
  ],
};
