module.exports = {
  sources: {
    head: {
      droop: "https://kemono.cafe/wp-content/uploads/2020/05/miko_head_droop.png",
      flop: "https://kemono.cafe/wp-content/uploads/2020/05/miko_head_flop.png",
      normal: "https://kemono.cafe/wp-content/uploads/2020/05/miko_head_normal.png",
      perked: "https://kemono.cafe/wp-content/uploads/2020/05/miko_head_perked.png",
    },
    eyebrow: {
      angry: "https://kemono.cafe/wp-content/uploads/2020/05/miko_eyebrow_angry.png",
      normal: "https://kemono.cafe/wp-content/uploads/2020/05/miko_eyebrow_normal.png",
      puzzled: "https://kemono.cafe/wp-content/uploads/2020/05/miko_eyebrow_puzzled.png",
      sad: "https://kemono.cafe/wp-content/uploads/2020/05/miko_eyebrow_sad.png",
      surprised: "https://kemono.cafe/wp-content/uploads/2020/05/miko_eyebrow_surprised.png",
    },
    eyes: {
      angry: "https://kemono.cafe/wp-content/uploads/2020/05/miko_eyes_angry.png",
      glee: "https://kemono.cafe/wp-content/uploads/2020/05/miko_eyes_glee.png",
      happy: "https://kemono.cafe/wp-content/uploads/2020/05/miko_eyes_happy.png",
      normal: "https://kemono.cafe/wp-content/uploads/2020/05/miko_eyes_normal.png",
      serious: "https://kemono.cafe/wp-content/uploads/2020/05/miko_eyes_serious.png",
      uu: "https://kemono.cafe/wp-content/uploads/2020/05/miko_eyes_uu.png",
    },
    mouth: {
      pout: "https://kemono.cafe/wp-content/uploads/2020/05/miko_mouth_pout.png",
      serious: "https://kemono.cafe/wp-content/uploads/2020/05/miko_mouth_serious.png",
      smile: "https://kemono.cafe/wp-content/uploads/2020/05/miko_mouth_smile.png",
      smileopen: "https://kemono.cafe/wp-content/uploads/2020/05/miko_mouth_smileopen.png",
      tongue: "https://kemono.cafe/wp-content/uploads/2020/05/miko_mouth_tongue.png",
      yell: "https://kemono.cafe/wp-content/uploads/2020/05/miko_mouth_yell.png",
    },
  },
  emotes: [
    {
      key: "miko_defeated",
      character: "miko",
      head: "flop",
      eyebrow: "sad",
      eyes: "uu",
      mouth: "pout",
    },
    {
      key: "miko_happy",
      character: "miko",
      head: "normal",
      eyebrow: "normal",
      eyes: "happy",
      mouth: "smile",
    },
    {
      key: "miko_inquisitive",
      character: "miko",
      head: "normal",
      eyebrow: "puzzled",
      eyes: "normal",
      mouth: "pout",
    },
    {
      key: "miko_playful",
      character: "miko",
      head: "normal",
      eyebrow: "normal",
      eyes: "uu",
      mouth: "tongue",
    },
    {
      key: "miko_sincere",
      character: "miko",
      head: "normal",
      eyebrow: "normal",
      eyes: "glee",
      mouth: "smile",
    },
    {
      key: "miko_sinister",
      character: "miko",
      head: "droop",
      eyebrow: "sad",
      eyes: "angry",
      mouth: "pout",
    },
    {
      key: "miko_squeal",
      character: "miko",
      head: "perked",
      eyebrow: "normal",
      eyes: "glee",
      mouth: "tongue",
    },
    {
      key: "miko_talk",
      character: "miko",
      head: "normal",
      eyebrow: "normal",
      eyes: "normal",
      mouth: "smileopen",
    },
    {
      key: "miko_yell",
      character: "miko",
      head: "perked",
      eyebrow: "angry",
      eyes: "angry",
      mouth: "serious",
    },
  ],
};
