module.exports = {
  sources: {
    head: {
      droop: "https://kemono.cafe/wp-content/uploads/2020/05/sandy_head_droop.png",
      normal: "https://kemono.cafe/wp-content/uploads/2020/05/sandy_head_normal.png",
      perked: "https://kemono.cafe/wp-content/uploads/2020/05/sandy_head_perked.png",
      puzzled: "https://kemono.cafe/wp-content/uploads/2020/05/sandy_head_puzzled.png",
    },
    eyebrow: {
      angry: "https://kemono.cafe/wp-content/uploads/2020/05/sandy_eyebrow_angry.png",
      normal: "https://kemono.cafe/wp-content/uploads/2020/05/sandy_eyebrow_normal.png",
      puzzled: "https://kemono.cafe/wp-content/uploads/2020/05/sandy_eyebrow_puzzled.png",
      sad: "https://kemono.cafe/wp-content/uploads/2020/05/sandy_eyebrow_sad.png",
      serious: "https://kemono.cafe/wp-content/uploads/2020/05/sandy_eyebrow_serious.png",
    },
    eyes: {
      angry: "https://kemono.cafe/wp-content/uploads/2020/05/sandy_eyes_angry.png",
      glee: "https://kemono.cafe/wp-content/uploads/2020/05/sandy_eyes_glee.png",
      happy: "https://kemono.cafe/wp-content/uploads/2020/05/sandy_eyes_happy.png",
      lookaway: "https://kemono.cafe/wp-content/uploads/2020/05/sandy_eyes_lookaway.png",
      normal: "https://kemono.cafe/wp-content/uploads/2020/05/sandy_eyes_normal.png",
      shocked: "https://kemono.cafe/wp-content/uploads/2020/05/sandy_eyes_shocked.png",
      squint: "https://kemono.cafe/wp-content/uploads/2020/05/sandy_eyes_squint.png",
      uu: "https://kemono.cafe/wp-content/uploads/2020/05/sandy_eyes_uu.png",
      x: "https://kemono.cafe/wp-content/uploads/2020/05/sandy_eyes_x.png",
    },
    mouth: {
      formal: "https://kemono.cafe/wp-content/uploads/2020/05/sandy_mouth_formal.png",
      pout: "https://kemono.cafe/wp-content/uploads/2020/05/sandy_mouth_pout.png",
      sad: "https://kemono.cafe/wp-content/uploads/2020/05/sandy_mouth_sad.png",
      serious: "https://kemono.cafe/wp-content/uploads/2020/05/sandy_mouth_serious.png",
      smile: "https://kemono.cafe/wp-content/uploads/2020/05/sandy_mouth_smile.png",
      smileopen: "https://kemono.cafe/wp-content/uploads/2020/05/sandy_mouth_smileopen.png",
      yell: "https://kemono.cafe/wp-content/uploads/2020/05/sandy_mouth_yell.png",
    },
  },
  emotes: [
    {
      key: "sandy_accepting",
      character: "sandy",
      head: "puzzled",
      eyebrow: "serious",
      eyes: "uu",
      mouth: "smile",
    },
    {
      key: "sandy_afraid",
      character: "sandy",
      head: "droop",
      eyebrow: "serious",
      eyes: "x",
      mouth: "pout",
    },
    {
      key: "sandy_awkward",
      character: "sandy",
      head: "droop",
      eyebrow: "puzzled",
      eyes: "lookaway",
      mouth: "smile",
    },
    {
      key: "sandy_complain",
      character: "sandy",
      head: "puzzled",
      eyebrow: "serious",
      eyes: "lookaway",
      mouth: "yell",
    },
    {
      key: "sandy_confused",
      character: "sandy",
      head: "puzzled",
      eyebrow: "puzzled",
      eyes: "lookaway",
      mouth: "serious",
    },
    {
      key: "sandy_cry",
      character: "sandy",
      head: "droop",
      eyebrow: "sad",
      eyes: "uu",
      mouth: "pout",
    },
    {
      key: "sandy_curious",
      character: "sandy",
      head: "perked",
      eyebrow: "serious",
      eyes: "happy",
      mouth: "serious",
    },
    {
      key: "sandy_doubt",
      character: "sandy",
      head: "perked",
      eyebrow: "puzzled",
      eyes: "squint",
      mouth: "serious",
    },
    {
      key: "sandy_excited",
      character: "sandy",
      head: "perked",
      eyebrow: "normal",
      eyes: "glee",
      mouth: "smileopen",
    },
    {
      key: "sandy_inquisitive",
      character: "sandy",
      head: "puzzled",
      eyebrow: "puzzled",
      eyes: "normal",
      mouth: "formal",
    },
    {
      key: "sandy_normal",
      character: "sandy",
      head: "normal",
      eyebrow: "normal",
      eyes: "normal",
      mouth: "smile",
    },
    {
      key: "sandy_plead",
      character: "sandy",
      head: "normal",
      eyebrow: "sad",
      eyes: "normal",
      mouth: "yell",
    },
    {
      key: "sandy_pout",
      character: "sandy",
      head: "droop",
      eyebrow: "puzzled",
      eyes: "lookaway",
      mouth: "pout",
    },
    {
      key: "sandy_rage",
      character: "sandy",
      head: "normal",
      eyebrow: "angry",
      eyes: "angry",
      mouth: "yell",
    },
    {
      key: "sandy_upset",
      character: "sandy",
      head: "normal",
      eyebrow: "sad",
      eyes: "shocked",
      mouth: "yell",
    },
    {
      key: "sandy_womp",
      character: "sandy",
      head: "puzzled",
      eyebrow: "serious",
      eyes: "uu",
      mouth: "pout",
    },
    {
      key: "sandy_worried",
      character: "sandy",
      head: "droop",
      eyebrow: "sad",
      eyes: "uu",
      mouth: "formal",
    },
  ],
};
