module.exports = {
  sources: {
    head: {
      normal: "https://kemono.cafe/wp-content/uploads/2020/05/steve_head_normal.png",
    },
    eyebrow: {
      broom: "https://kemono.cafe/wp-content/uploads/2020/05/steve_eyebrow_broom.png",
      cap: "https://kemono.cafe/wp-content/uploads/2020/05/steve_eyebrow_cap.png",
      pringles: "https://kemono.cafe/wp-content/uploads/2020/05/steve_eyebrow_pringles.png",
    },
    eyes: {
      angry: "https://kemono.cafe/wp-content/uploads/2020/05/steve_eyes_angry.png",
      closed: "https://kemono.cafe/wp-content/uploads/2020/05/steve_eyes_closed.png",
      female: "https://kemono.cafe/wp-content/uploads/2020/05/steve_eyes_female.png",
      normal: "https://kemono.cafe/wp-content/uploads/2020/05/steve_eyes_normal.png",
      shocked: "https://kemono.cafe/wp-content/uploads/2020/05/steve_eyes_shocked.png",
      sleepy: "https://kemono.cafe/wp-content/uploads/2020/05/steve_eyes_sleepy.png",
    },
    mouth: {
      bigoh: "https://kemono.cafe/wp-content/uploads/2020/05/steve_mouth_bigoh.png",
      bigsmile: "https://kemono.cafe/wp-content/uploads/2020/05/steve_mouth_bigsmile.png",
      formal: "https://kemono.cafe/wp-content/uploads/2020/05/steve_mouth_formal.png",
      grin: "https://kemono.cafe/wp-content/uploads/2020/05/steve_mouth_grin.png",
      kissy: "https://kemono.cafe/wp-content/uploads/2020/05/steve_mouth_kissy.png",
      pout: "https://kemono.cafe/wp-content/uploads/2020/05/steve_mouth_pout.png",
      serious: "https://kemono.cafe/wp-content/uploads/2020/05/steve_mouth_serious.png",
      talk: "https://kemono.cafe/wp-content/uploads/2020/05/steve_mouth_talk.png",
      upset: "https://kemono.cafe/wp-content/uploads/2020/05/steve_mouth_upset.png",
      yell: "https://kemono.cafe/wp-content/uploads/2020/05/steve_mouth_yell.png",
    },
  },
  emotes: [
    {
      key: "steve_attendant_concerned",
      character: "steve",
      head: "normal",
      eyebrow: "cap",
      eyes: "sleepy",
      mouth: "formal",
    },
    {
      key: "steve_attendant_confused",
      character: "steve",
      head: "normal",
      eyebrow: "cap",
      eyes: "closed",
      mouth: "formal",
    },
    {
      key: "steve_attendant_frustrated",
      character: "steve",
      head: "normal",
      eyebrow: "cap",
      eyes: "closed",
      mouth: "upset",
    },
    {
      key: "steve_attendant_suggest",
      character: "steve",
      head: "normal",
      eyebrow: "cap",
      eyes: "sleepy",
      mouth: "talk",
    },
    {
      key: "steve_manager_exhausted",
      character: "steve",
      head: "normal",
      eyebrow: "broom",
      eyes: "sleepy",
      mouth: "serious",
    },
    {
      key: "steve_manager_firm",
      character: "steve",
      head: "normal",
      eyebrow: "broom",
      eyes: "angry",
      mouth: "formal",
    },
    {
      key: "steve_manager_inquisitive",
      character: "steve",
      head: "normal",
      eyebrow: "broom",
      eyes: "normal",
      mouth: "serious",
    },
    {
      key: "steve_manager_speaking",
      character: "steve",
      head: "normal",
      eyebrow: "broom",
      eyes: "normal",
      mouth: "talk",
    },
  ],
};
